// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import PropertyCarouselController from "./property_carousel_controller"
application.register("property-carousel", PropertyCarouselController)

import SearchController from "./search_controller"
application.register("search", SearchController)
